baseURL: "https://willyoulove.me"
languageCode: en-us
title: Keit's blog
theme: PaperMod


#Hero section ↓
params:
  homeInfoParams:
    Title: Hi, I'm Kiệt 👋
    Content: Sample text since 2022.
assets:
  favicon: "/favicon.ico"
  favicon16x16:  "/favicon-16x16.png"
  favicon32x32:  "/favicon-32x32.png"
  apple_touch_icon:  "/apple-touch-icon.png"
  safari_pinned_tab:  "/safari-pinned-tab.svg"


#Menu section ↓
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: archives
      name: Archives
      url: /Archives/
      weight: 20
    # - identifier: about
    #   name: About
    #   url: /About/
    #   weight: 30